# Generated by Django 3.1.5 on 2021-01-15 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('content', models.TextField(max_length=500)),
                ('image', models.FileField(upload_to='')),
                ('iframe', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Male Group', 'Male Group'), ('Female Group', 'Female Group'), ('Male SOLO', 'Male SOLO'), ('Female SOLO', 'Female SOLO')], max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_long', models.CharField(max_length=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.commodity')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.singer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact Phone Number', max_length=31)),
                ('address', models.CharField(max_length=100)),
                ('pay', models.CharField(choices=[('貨到付款', '貨到付款'), ('銀行轉帳', '銀行轉帳'), ('信用卡支付', '信用卡支付')], max_length=100)),
                ('status', models.CharField(choices=[('備貨中', '備貨中'), ('運貨中', '運貨中'), ('當天送達', '當天送達')], default='備貨中', max_length=100)),
                ('progress', models.CharField(choices=[('未付款', '未付款'), ('已付款', '已付款'), ('交易完成', '交易完成')], default='未付款', max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commodity.commodity')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('music_files', models.FileField(upload_to='')),
                ('singer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commodity.singer')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.singer'),
        ),
    ]
